- defaults:
    link:
      relink: true
      create: true

- clean: ['~']

- link:
    ~/.bashrc:
    ~/.zshrc:
    ~/.zsh_themes:
    ~/.vimrc:
    ~/.oh-my-zsh: 
    ~/.iterm2: 
    ~/.config:
    ~/.gitignore_global:
    ~/.gitconfig:
    ~/.ssh/config: ssh/config

- shell:
  -
    command: ./scripts/macos_defaults.zsh
    stdin: true
    stdout: true
    stderr: true
  -
    command: ./scripts/setup_homebrew.zsh
    stdin: true
    stdout: true
    stderr: true
