- defaults:
    link:
      relink: true

- clean: ['~']

- link:
    ~/.bashrc:
    ~/.zshrc:
    ~/.zsh_themes:
    ~/.vimrc:
    ~/.oh-my-zsh: 
    ~/.iterm2: 
    ~/.config:
    ~/.fig:
    ~/.yabairc:
    ~/.skhdrc:
    ~/.gitignore_global:
    ~/.gitconfig:
    ~/.ssh:

- shell:
  - [git submodule update --init --recursive, Installing submodules]
  -
    command: ./scripts/setup_homebrew.zsh
    stdin: true
    stdout: true
    stderr: true
