#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.85
yabai -m config window_border                on
yabai -m config window_border_width          6
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config normal_window_border_color   0xffA282C3
yabai -m config active_window_border_color   0xff61AFEF
# Colors: Grey ABB2BF, blue: 61AFEF, red: E06C75, purple: C678DD, dark: 282C34

#yabai -m config normal_window_border_color   0xff555555
#yabai -m config active_window_border_color   0xffC678DD
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap
# set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier fn

# set modifier + left-click drag to resize window (default: move)
yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize

# general space settings
yabai -m config layout                       bsp
#yabai -m config bottom_padding               12
#yabai -m config left_padding                 12
#yabai -m config right_padding                12
#yabai -m config window_gap                   06

# yabai -m config bottom_padding               0
# yabai -m config left_padding                 0
# yabai -m config right_padding                0
# yabai -m config window_gap                   0

# Perfect padding with siri shortcuts
yabai -m config bottom_padding              15
yabai -m config left_padding                15
yabai -m config right_padding               15
yabai -m config top_padding                 15
yabai -m config window_gap                   20


#yabai -m rule --add app="Spotify"            space=9
yabai -m rule --add app="^System Preferences$" manage=off
# yabai -m rule --add app="Code" opacity=0.85
# yabai -m rule --add app="Neovide" opacity=0.85
#yabai -m rule --add app="^Finder$" manage=off
#yabai -m rule --add app="^Steam$" manage=off

yabai -m config top_padding                  46
yabai -m config top_padding                  20
yabai -m config top_padding                  46
yabai -m config top_padding                  20
yabai -m config top_padding                  46
yabai -m config top_padding                  20
yabai -m config top_padding                  46
