name: verify-themes-uniqueness
on: [push, pull_request]
jobs:
  verify-theme-uniqueness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./.github/scripts/theme-uniqueness.sh

