--Vapour.utils.plugins.add_user({'drewtempelmeyer/palenight.vim'})
--Vapour.utils.plugins.add_user({'nacro90/numb.nvim', {config = function() require'numb'.setup{show_numbers = false} end}})
--
--vim.g.termguicolors=true
--vim.o.termguicolors = true
--vim.o.background = 'dark'
--
--vim.cmd('colorscheme palenight')
--Vapour.settings.colorscheme = 'palenight'
--
-- Example config in Lua
-- vim.g.tokyonight_style = "night"
-- vim.g.tokyonight_italic_functions = false
-- vim.g.tokyonight_italic_comments = false
-- vim.g.tokyonight_italic_keywords = false
-- vim.g.tokyonight_sidebars = { "qf", "vista_kind", "terminal", "packer" }
--
-- Change the "hint" color to the "orange" color, and make the "error" color bright red
-- vim.g.tokyonight_colors = { hint = "orange", error = "#ff0000" }
--
-- Load the colorscheme
--
--Vapour.plugins.user = {
--  {'lervag/vimtex'}
--}
