---@meta

---@class unknown
---@class any
---@class nil
---@class boolean
---@class number
---@alias integer number
---@class thread
---@class table
---@class string
---@class userdata
---@class lightuserdata
---@class function
